
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
// import Typography from '@mui/material/Typography';
import * as m from "@mui/material";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <header>
          <m.Stack >
          <m.Typography variant="h2" >
            <m.Stack alignItems={"center"}>
            Car Galaxy Inventory

            </m.Stack>
          <m.Divider orientation="horizontal" /> 

          </m.Typography>

          </m.Stack>
          
        
          
        </header>
        {children}
      </AppRouterCacheProvider>
        </body>
    </html>
  )
}
